groups:
  - name: proof-health-alerts
    rules:
      - alert: ProofArtifactMissing
        expr: proof_health_artifact_present == 0
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: "Proof artifact missing"
          description: "Latest proof artifact is missing for {{ $labels.proof }}."

      - alert: ProofArtifactFailed
        expr: proof_health_artifact_ok == 0
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: "Proof artifact reports failure"
          description: "Latest proof artifact for {{ $labels.proof }} reports non-ok."

      - alert: ProofHealthDegraded
        expr: proof_health_overall_ok == 0
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "Proof health degraded"
          description: "At least one proof artifact is missing or failing."

      - alert: ProofHealthMissingArtifacts
        expr: proof_health_missing_count > 0
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Missing proof artifacts detected"
          description: "{{ $value }} proof artifacts are missing."

      - alert: ProofArtifactStale
        expr: proof_health_artifact_age_seconds > 604800
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: "Proof artifact stale"
          description: "Proof artifact for {{ $labels.proof }} is older than 7 days."

      - alert: RunbookRequiresOperatorAction
        expr: proof_health_runbook_recommended_action{action!="NO_ACTION"} == 1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Runbook recommends follow-up action"
          description: "Runbook {{ $labels.runbook }} recommends {{ $labels.action }}."
  - name: mapping-coverage-alerts
    rules:
      - alert: MappingCoverageMetricsExportFailed
        expr: mapping_coverage_export_ok == 0
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "Mapping coverage metrics export failed"
          description: "Latest mapping coverage metrics artifact could not be exported."

      - alert: MappingCoverageDegraded
        expr: mapping_coverage_overall_ok == 0
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "Mapping coverage health degraded"
          description: "Coverage ratio or mapping integrity counters are out of threshold."

      - alert: MappingCoverageRunbookActionRequired
        expr: mapping_coverage_runbook_recommended_action{action!="NO_ACTION"} == 1
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Mapping coverage runbook follow-up required"
          description: "Runbook recommends {{ $labels.action }} for mapping coverage remediation."
