groups:
  - name: ledger-reconciliation
    rules:
      - alert: LedgerReconciliationBreachActive
        expr: reconciliation_breach_active > 0
        for: 1m
        labels:
          severity: critical
          service: ledger-service
        annotations:
          summary: "Ledger reconciliation breach is active"
          description: "At least one symbol has lag above threshold, mismatch, or stale reconciliation state."

      - alert: LedgerReconciliationStateStale
        expr: increase(reconciliation_stale_total[5m]) > 0
        for: 0m
        labels:
          severity: warning
          service: ledger-service
        annotations:
          summary: "Reconciliation state stale breach observed"
          description: "A symbol exceeded reconciliation state freshness threshold in the last 5 minutes."

      - alert: LedgerReconciliationSafetyTriggered
        expr: increase(reconciliation_safety_trigger_total[5m]) > 0
        for: 0m
        labels:
          severity: warning
          service: ledger-service
        annotations:
          summary: "Safety mode auto-triggered by reconciliation"
          description: "Ledger reconciliation triggered symbol safety mode in the last 5 minutes."

      - alert: LedgerReconciliationSafetyApplyFailed
        expr: increase(reconciliation_safety_failure_total[5m]) > 0
        for: 0m
        labels:
          severity: critical
          service: ledger-service
        annotations:
          summary: "Safety mode trigger attempt failed"
          description: "Ledger reconciliation detected a breach but could not apply safety mode."

      - alert: LedgerLatchReleaseDenied
        expr: increase(reconciliation_latch_release_denied_total[10m]) > 0
        for: 0m
        labels:
          severity: warning
          service: ledger-service
        annotations:
          summary: "Reconciliation latch release denied"
          description: "One or more manual latch release attempts were denied in the last 10 minutes."

      - alert: LedgerLatchReleaseDeniedSpike
        expr: increase(reconciliation_latch_release_denied_total[10m]) >= 3
        for: 0m
        labels:
          severity: critical
          service: ledger-service
        annotations:
          summary: "Repeated latch release denial spike"
          description: "Three or more latch release denials occurred in 10 minutes; investigate release conditions or approval flow."
