apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exchange-platform-dev
  namespace: argocd
  labels:
    exchange.quanta.io/environment: dev
spec:
  project: exchange-platform
  source:
    repoURL: https://github.com/quanta-exchange/exchange-platform.git
    targetRevision: main
    path: infra/k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
