CREATE TABLE IF NOT EXISTS accounts (
    account_id VARCHAR(128) PRIMARY KEY,
    user_id VARCHAR(128),
    currency VARCHAR(32) NOT NULL,
    account_kind VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ledger_entries (
    entry_id VARCHAR(64) PRIMARY KEY,
    reference_type VARCHAR(64) NOT NULL,
    reference_id VARCHAR(128) NOT NULL,
    entry_kind VARCHAR(64) NOT NULL,
    symbol VARCHAR(64) NOT NULL,
    engine_seq BIGINT NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    correlation_id VARCHAR(128) NOT NULL,
    causation_id VARCHAR(128) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UNIQUE(reference_type, reference_id, entry_kind)
);

CREATE TABLE IF NOT EXISTS ledger_postings (
    posting_id VARCHAR(64) PRIMARY KEY,
    entry_id VARCHAR(64) NOT NULL REFERENCES ledger_entries(entry_id),
    account_id VARCHAR(128) NOT NULL REFERENCES accounts(account_id),
    currency VARCHAR(32) NOT NULL,
    amount BIGINT NOT NULL,
    is_debit BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS settlement_dlq (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_id VARCHAR(128) NOT NULL,
    reason TEXT NOT NULL,
    payload TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS settlement_idempotency (
    trade_id VARCHAR(128) PRIMARY KEY,
    ledger_entry_id VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS account_balances (
    account_id VARCHAR(128) NOT NULL,
    currency VARCHAR(32) NOT NULL,
    balance BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY(account_id, currency)
);

CREATE TABLE IF NOT EXISTS reconciliation_state (
    symbol VARCHAR(64) PRIMARY KEY,
    last_engine_seq BIGINT NOT NULL DEFAULT 0,
    last_settled_seq BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS invariant_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_kind VARCHAR(64) NOT NULL,
    details TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS correction_requests (
    correction_id VARCHAR(64) PRIMARY KEY,
    original_entry_id VARCHAR(64) NOT NULL,
    mode VARCHAR(32) NOT NULL,
    reason TEXT NOT NULL,
    ticket_id VARCHAR(128) NOT NULL,
    requested_by VARCHAR(128) NOT NULL,
    approver1 VARCHAR(128),
    approver2 VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    approved_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_ledger_entries_symbol_seq ON ledger_entries(symbol, engine_seq);
CREATE INDEX IF NOT EXISTS idx_ledger_postings_entry ON ledger_postings(entry_id);
CREATE INDEX IF NOT EXISTS idx_correction_status_created ON correction_requests(status, created_at);
