CREATE TABLE IF NOT EXISTS reconciliation_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(64) NOT NULL,
    last_engine_seq BIGINT NOT NULL,
    last_settled_seq BIGINT NOT NULL,
    lag BIGINT NOT NULL,
    mismatch BOOLEAN NOT NULL DEFAULT FALSE,
    threshold BIGINT NOT NULL,
    breached BOOLEAN NOT NULL DEFAULT FALSE,
    safety_mode VARCHAR(32),
    safety_action_taken BOOLEAN NOT NULL DEFAULT FALSE,
    reason TEXT NOT NULL,
    checked_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS reconciliation_safety_state (
    symbol VARCHAR(64) PRIMARY KEY,
    breach_active BOOLEAN NOT NULL DEFAULT FALSE,
    last_lag BIGINT NOT NULL DEFAULT 0,
    last_mismatch BOOLEAN NOT NULL DEFAULT FALSE,
    safety_mode VARCHAR(32),
    last_action_taken BOOLEAN NOT NULL DEFAULT FALSE,
    reason TEXT,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    last_action_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_reconciliation_history_symbol_checked
    ON reconciliation_history(symbol, checked_at DESC);

